apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mxl-hello.fullname" . }}-flow-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mxl-hello.labels" . | nindent 4 }}
    dmf.component: flow-config
data:
  flow.json: {{ .Values.flow.json | toJson }}
