on: [push, pull_request]
jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - run: pip install ansible ansible-lint yamllint
      - run: yamllint -s .
      - run: ansible-lint playbooks/ -p
      - run: |
          for pb in playbooks/*.yml; do
            ansible-playbook --syntax-check "$pb" || exit 1
          done
