apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mxl-fabrics-demo.name" . }}-node-reader
  labels:
    {{- include "mxl-fabrics-demo.labels" . | nindent 4 }}
    dmf.component: mxl-status-sidecar
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mxl-fabrics-demo.name" . }}-node-reader
  labels:
    {{- include "mxl-fabrics-demo.labels" . | nindent 4 }}
    dmf.component: mxl-status-sidecar
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}
  - kind: ServiceAccount
    name: mxl-view
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mxl-fabrics-demo.name" . }}-node-reader
