apiVersion: v1
kind: Service
metadata:
  name: nmos-cpp-registry
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nmos-cpp.nmosLabels" . | nindent 4 }}
    dmf.component: registry
spec:
  type: ClusterIP
  selector:
    app: nmos-cpp-registry
  ports:
    - protocol: TCP
      port: {{ .Values.nmosConfig.httpPort }}
      targetPort: {{ .Values.nmosConfig.httpPort }}
      name: http
